<?php
return array(
    'EXAM_GROUP_TYPES'=>array('高思杯'=>'高思杯',
                              '精英赛'=>'精英赛',
                              '补录考试'=>'补录考试',
                              '迎春杯'=>'迎春杯',
                              '春蕾杯'=>'春蕾杯', 
                              '希望杯'=>'希望杯',
                              '华杯赛'=>'华罗庚金杯邀请赛',
                              '走美杯'=>'走美杯',
                              'AMC'   =>'AMC',
                              '入学测试'=>'入学测试',
                              '班级测试'=>'班级测试',
                              '小数等级考试'=>'小数等级考试',
                              '其他'=>'其他'),
    'WEB_EXCEPT_TYPES'=>array('入学测试','班级测试'),
    'EXAM_SUBJECTS' =>array('1001-math'=>'小学数学',
                            '1002-chinese'=>'小学语文',
                            '1003-english'=>'小学英语',
                            '2001-math'=>'初中数学',
                            '2002-chinese'=>'初中语文',
                            '2003-english'=>'初中英语',
                            '2004-physic'=>'初中物理',
                            '2005-chemistry'=>'初中化学',
                            '3001-math'=>'高中数学',
                            '3002-chinese'=>'高中语文',
                            '3003-english'=>'高中英语',
                            '3004-physic'=>'高中物理',
                            '3005-chemistry'=>'高中化学'),
                            
	'SUBJECT_XUEBUKE'=>array('1001-math'=>'1001',
                            '1002-chinese'=>'1002',
                            '1003-english'=>'1003',
                            '2001-math'=>'2001',
                            '2002-chinese'=>'2002',
                            '2003-english'=>'2003',
                            '2004-physic'=>'2004',
                            '2005-chemistry'=>'2005',
                            '3001-math'=>'3001',
                            '3002-chinese'=>'3002',
                            '3003-english'=>'3003',
                            '3004-physic'=>'3004',
                            '3005-chemistry'=>'3005'),
    'EXAM_PAPER_TYPES'=>array('实体卷'=>'实体卷',
                              '附加卷'=>'附加卷',
                              '虚拟卷'=>'虚拟卷'),
	'AWARD_TPL_DIR'	=>APP_DIR . '/AwardTplDir/',
	'FONT_DIR'		=>APP_DIR . '/Static/fonts/',
	'AWARD_UPLOAD_CONFIG' => array('allowTypes'=>array('image/jpeg', 'image/pjpeg', 'image/png', 'image/gif'),
								   'allowExts'=>array('gif','jpg', 'jpeg', 'png'),
                               	   'saveRule'=>'time',
                               	   'thumb'=>true,
                               	   'thumbMaxWidth'=>750,
                               	   'thumbMaxHeight'=>700,
                               	   'uploadReplace'=>true),
    'AREA_ARRAY'=>array('海淀区','朝阳区','东城区','西城区','崇文区','宣武区','丰台区','石景山区','昌平区','顺义区','大兴区','房山区'),
    'FONT_ARRAY'=>array('simhei'=>'黑体', 'simli'=>'隶书', 'simsun'=>'宋体', 'simkai'=>'楷体', 'msyh'=>'微软雅黑', 'msyhbd'=>'雅黑粗体'),
    'COLOR_ARRAY'=>array('black'=>array('黑色', '0,0,0', '#000'),
    					 'red'=>array('红色','255,0,0', '#f00'),
    					 'blue'=>array('蓝色','0,0,255', '#00f')),
)
?>